# Generated by Django 5.1.7 on 2025-03-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_product_quantity"),
        ("mix_and_match", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useroutfit",
            name="clothing_items",
        ),
        migrations.CreateModel(
            name="OutfitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("scale", models.FloatField(default=1.0)),
                ("z_index", models.IntegerField(default=0)),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="mix_and_match.useroutfit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
    ]
