# Generated by Django 5.1 on 2025-04-30 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix_and_match', '0002_remove_useroutfit_clothing_items_outfititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.ImageField(upload_to='ai_outfits/')),
                ('critique', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='mix_and_match.useroutfit')),
            ],
        ),
    ]
