# Generated by Django 5.1 on 2025-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix_and_match', '0004_outfititem_modified_at_useroutfit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroutfit',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make this outfit visible on your public profile?'),
        ),
    ]
