# Generated by Django 5.0 on 2025-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck for a private item (personal closet)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('TOPS', 'Tops'), ('BOTTOMS', 'Bottoms'), ('DRESSES', 'Dresses'), ('OUTERWEAR', 'Outerwear'), ('ACCESSORIES', 'Accessories')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('NWT', 'New with tags'), ('EU', 'Excellent used'), ('GU', 'Good used'), ('FU', 'Fair used')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
