# Generated by Django 5.1 on 2025-04-29 17:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='appearance_prompt_notes',
            field=models.TextField(blank=True, help_text="Optional: Other distinct features for AI prompts (e.g., 'long wavy brown hair', 'wears round glasses', 'visible tattoo on left forearm').", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='body_type_ai',
            field=models.CharField(blank=True, help_text='Optional: Helps AI visualize appearance (e.g., Slim, Athletic, Average, Stocky, Curvy, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity_ai',
            field=models.CharField(blank=True, help_text='Optional: Helps AI visualize appearance (e.g., Filipino, East Asian, Caucasian, Hispanic, Black, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Your height in centimeters (e.g., 165).', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Optional: Your weight in kilograms (e.g., 68.5).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.0')), django.core.validators.MaxValueValidator(Decimal('300.0'))]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short description about yourself.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., City, Province', max_length=255, null=True),
        ),
    ]
