# Generated by Django 5.1 on 2025-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_role_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary / Gender-diverse'), ('unknown', 'Prefer not to say / Let AI infer')], default='unknown', help_text='Optional: lets the AI choose better outfits; leave blank to let it infer.', max_length=20),
        ),
    ]
