# Generated by Django 5.1 on 2025-04-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='PH', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
